### ISSUE TITLE
[Bug] Very rare crash loop because of android.hardware.camera.provider@2.4-service_64

### ISSUE THREAD

**Issue by MartinX3** [MartinX3-AndroidDevelopment-LineageOS/bug_tracker#12]
**Platform:** TAMA
**Device:** AKARI
**Kernel version:** 4.14
**Android version:** 10.0

**Description**
Very very rarely the phone gets into a crash loop until I force a restart with the hardware buttons.

**Symptoms**
Lineage Logo loop and and sometimes blinking screen

**How to reproduce**
Happens in the screen is off.

**Additional context**
Stacktrace shows the /vendor/bin/hw/android.hardware.camera.provider@2.4-service_64 using the camera.sdm845.so.
[logcat_-b_all.log](https://github.com/MartinX3-AndroidDevelopment-LineageOS/bug_tracker/files/4573750/logcat_-b_all.log)

**Comment by KittyByte** [comment]
Yesterday I noticed that my camera stopped working, and it seems that the problem is because of him because he works 24/7 and does not allow me to use the camera
![Screenshot_2024-09-15-08-45-19-978_com miui securitycenter](https://github.com/user-attachments/assets/c3526ca6-2638-439e-baa7-10c9105f71da)
![Screenshot_2024-09-15-08-49-24-367_com miui securitycenter](https://github.com/user-attachments/assets/ef7e0a77-630e-4b9d-8b04-0434fbd70552)

**Comment by MartinX3** [comment]
This was for Android 10 / LineageOS 17.1.
Now there is LineageOS 21 on XDA maintained by a different developer.
(I don't had the time to continue this project)
